title: ヨガ部 | Bukatsudo Yoga
email: mkataoka73@gmail.com
description: This site is a demo site created by a member of Bukatsudo Yoga club.

baseurl: "/bukatsudoyoga"
url: "https://jlmercury.github.io"

collections:
  - members
