title: ヨガ部 | Bukatsudo Yoga
email: mkataoka73@gmail.com
description: This site is a site created by a member of Bukatsudo Yoga club.

baseurl: "/bukatsudoyoga"

future: true
timezone: Asia/Tokyo

google_analytics: UA-150948074-1

sass:
  style: expanded

collections:
   members:
     name:
       yossie: yossie
       kanako: kanako
     icon:
       yossie: /bukatsudoyoga/assets/images/photo/prof/mkataoka.jpg
       kanaco: /bukatsudoyoga/assets/images/photo/prof/1.jpg
     output: true
   events:
     output: true
