title: ヨガ部 | Bukatsudo Yoga
email: mkataoka73@gmail.com
description: This site is a demo site created by a member of Bukatsudo Yoga club.

url: "https://jlmercury.github.io"

future: true
timezone: Asia/Tokyo

collections:
   members:
   events:
     output: true
