title: ヨガ部 | Bukatsudo Yoga
email:
description: This site is a demo site created by a member of Bukatsudo Yoga club.

baseurl: "/bukatsudo_yoga"
url: "https://jlmercury.github.io"

collections:
  - members
