title: ヨガ部 | Bukatsudo Yoga
email: mkataoka73@gmail.com
description: This site is a demo site created by a member of Bukatsudo Yoga club.

baseurl: "/bukatsudoyoga"

future: true
timezone: Asia/Tokyo

collections:
   members:
     name:
       yossie: yossie
       kanako: kanako
     icon:
       yossie: /bukatsudoyoga/images/photo/prof/mkataoka.jpg
       kanaco: /bukatsudoyoga/images/photo/prof/kanaco3.jpg
     output: true
   events:
     output: true
